#!/bin/bash
if [ $# -ne 0 ];then
    if [ -f $1 ];then
	for a in $(cat $1)
		do 
		  useradd -s /bin/false $a
		  echo "用户$a创建成功"
		done
	exit 0
    else 
	echo "Input file not found"
 	exit 1
    fi
else
  echo "Usage:/root/batchusers<userfile>"
  exit 2
fi 
